name: Go eBPF CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  build:

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm gcc-multilib
          clang --version
          llc --version

      - name: Build eShuffuler
        working-directory: .
        run: |
          make
          make run
          zip eShuffler.zip scripts/conf.yaml scripts/run.sh bin/traffic-shuffler

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest"
          title: "Development Build"
          files: |
            eShuffler.zip
