name: Go eBPF CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm gcc-multilib
          clang --version
          llc --version

      - name: Build eShuffuler
        working-directory: .
        run: |
          make

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            scripts/conf.yaml
            scripts/run.sh
            bin/traffic-shuffler
